$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1.2
        },
        600:{
            items:3.2
        },
        1000:{
            items:5.2
        }
    }
})